/*
 * Data Repository Service
 *  GET request:  - Fetch a DrsObject from the database by sending a unique ID through the request - Fetch an access url to the data which the object refers to - Fetch DrsObjects by doing a search on the aliases  POST request:  - Create a non-existing DrsObject in the database by giving an identifier  DELETE request:  - Delete a DrsObject from the database by unique identifier  PUT request:  - Update an existing DrsObject by unique identifier and the changes in the body 
 *
 * OpenAPI spec version: 1.2.0
 * Contact: ict@cmgg.be
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.client.model.AccessURL;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
/**
 * AccessMethods
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2024-06-25T15:49:43.145836023+02:00[Europe/Brussels]")

public class AccessMethods {
  @SerializedName("type")
  private String type = null;

  @SerializedName("access_url")
  private AccessURL accessUrl = null;

  @SerializedName("access_id")
  private String accessId = null;

  @SerializedName("region")
  private String region = null;

  public AccessMethods type(String type) {
    this.type = type;
    return this;
  }

   /**
   * Enum: &#x60;&#x60;&#x60;\&quot;s3\&quot;&#x60;&#x60;&#x60; &#x60;&#x60;&#x60;\&quot;gs\&quot;&#x60;&#x60;&#x60; &#x60;&#x60;&#x60;\&quot;ftp\&quot;&#x60;&#x60;&#x60; &#x60;&#x60;&#x60;\&quot;gsiftp\&quot;&#x60;&#x60;&#x60; &#x60;&#x60;&#x60;\&quot;globus\&quot;&#x60;&#x60;&#x60;         &#x60;&#x60;&#x60;\&quot;htsget\&quot;&#x60;&#x60;&#x60; &#x60;&#x60;&#x60;\&quot;https\&quot;&#x60;&#x60;&#x60; &#x60;&#x60;&#x60;\&quot;file\&quot;&#x60;&#x60;&#x60; Type of the access method.
   * @return type
  **/
  @Schema(required = true, description = "Enum: ```\"s3\"``` ```\"gs\"``` ```\"ftp\"``` ```\"gsiftp\"``` ```\"globus\"```         ```\"htsget\"``` ```\"https\"``` ```\"file\"``` Type of the access method.")
  public String getType() {
    return type;
  }

  public void setType(String type) {
    this.type = type;
  }

  public AccessMethods accessUrl(AccessURL accessUrl) {
    this.accessUrl = accessUrl;
    return this;
  }

   /**
   * Get accessUrl
   * @return accessUrl
  **/
  @Schema(description = "")
  public AccessURL getAccessUrl() {
    return accessUrl;
  }

  public void setAccessUrl(AccessURL accessUrl) {
    this.accessUrl = accessUrl;
  }

  public AccessMethods accessId(String accessId) {
    this.accessId = accessId;
    return this;
  }

   /**
   * An arbitrary string to be passed to the &#x60;&#x60;&#x60;/access&#x60;&#x60;&#x60; method to get an &#x60;&#x60;&#x60;AccessURL&#x60;&#x60;&#x60;.         This string must be unique within the scope of a single object. Note that at least one         of &#x60;&#x60;&#x60;access_url&#x60;&#x60;&#x60; and &#x60;&#x60;&#x60;access_id&#x60;&#x60;&#x60; must be provided.
   * @return accessId
  **/
  @Schema(description = "An arbitrary string to be passed to the ```/access``` method to get an ```AccessURL```.         This string must be unique within the scope of a single object. Note that at least one         of ```access_url``` and ```access_id``` must be provided.")
  public String getAccessId() {
    return accessId;
  }

  public void setAccessId(String accessId) {
    this.accessId = accessId;
  }

  public AccessMethods region(String region) {
    this.region = region;
    return this;
  }

   /**
   * Name of the region in the cloud service provider that the object belongs to.
   * @return region
  **/
  @Schema(description = "Name of the region in the cloud service provider that the object belongs to.")
  public String getRegion() {
    return region;
  }

  public void setRegion(String region) {
    this.region = region;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    AccessMethods accessMethods = (AccessMethods) o;
    return Objects.equals(this.type, accessMethods.type) &&
        Objects.equals(this.accessUrl, accessMethods.accessUrl) &&
        Objects.equals(this.accessId, accessMethods.accessId) &&
        Objects.equals(this.region, accessMethods.region);
  }

  @Override
  public int hashCode() {
    return Objects.hash(type, accessUrl, accessId, region);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class AccessMethods {\n");
    
    sb.append("    type: ").append(toIndentedString(type)).append("\n");
    sb.append("    accessUrl: ").append(toIndentedString(accessUrl)).append("\n");
    sb.append("    accessId: ").append(toIndentedString(accessId)).append("\n");
    sb.append("    region: ").append(toIndentedString(region)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
